import lcd
import time


def main():  # Main program block
    lcd.begin()
    time.sleep(3)
    lcd.clear()
    lcd.waitPage()
    time.sleep(3)
    lcd.clear()
    lcd.welcomePage('Dao Minh An', 'B1509360', 7)
    time.sleep(3)
    lcd.clear()
    lcd.addExtraInfoPage('Dao Minh An', 'B1509360')
    lcd.pointerPos(2, 1)
    lcd.clear()
    lcd.welcomeTempPage(9)
    time.sleep(3)
    lcd.clear()
    lcd.unknownIDPage()
    time.sleep(3)
    lcd.clear()
    lcd.addFingerPage(1)
    time.sleep(3)
    lcd.clear()
    lcd.addFingerSuccessPage()
    time.sleep(3)
    lcd.clear()
    lcd.addFingerFailPage()
    time.sleep(3)
    lcd.clear()
    lcd.addRFIDPage()
    time.sleep(3)
    lcd.clear()
    lcd.addRFIDSuccessPage()
    time.sleep(3)
    lcd.clear()
    lcd.addRFIDFailPage()
    time.sleep(3)
    lcd.clear()
    lcd.addInfoPage()
    time.sleep(3)
    lcd.clear()
    lcd.mainDatabasePage()
    time.sleep(3)
    lcd.clear()
    lcd.exportSuccessPage()
    time.sleep(3)
    lcd.clear()
    lcd.exportFailPage()
    time.sleep(3)
    lcd.clear()
    lcd.importPage()
    time.sleep(3)
    lcd.clear()
    lcd.importSuccessPage()
    time.sleep(3)
    lcd.clear()
    lcd.importFailPage()
    time.sleep(3)
    lcd.clear()
    lcd.mainLockerPage()
    time.sleep(3)
    lcd.clear()
    lcd.infoLockerPage('Dao Minh An', 'B1509360')
    time.sleep(3)
    lcd.clear()
    lcd.infoLockerTempPage()
    time.sleep(3)
if __name__ == '__main__':

    try:
        main()
    except KeyboardInterrupt:
        pass
